server:
  port:8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/customers
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password123
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka
